version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo Migration started on `date`
      - echo Migrating using Prisma
      - npx prisma migrate deploy
  post_build:
    commands:
      - echo Migration completed on `date`
